server:
  port: 8081

spring:
  application:
    name: fraud
    datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5433/customer
      username: postgres
      password: afshar
    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          enable_lazy_load_no_trans: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect