version: '3.7'

services:
  currency-conversion:
    image: currency-conversion-service
    ports:
      - "8100:8100"
    networks:
      - currency-network
    depends_on:
      - eureka-server
#    environment:
#      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eureka-server:8761/eureka #write in applicaion.propertis
#      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/ # write in Dockerfile

  currency-exchange:
    image: currency-exchange-service
    ports:
      - "8000:8000"
    networks:
      - currency-network
    depends_on:
      - eureka-server
#    environment:
#      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eureka-server:8761/eureka #write in applicaion.propertis
#      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/ # write in Dockerfile

  api-gateway:
    image: api-gateway
    ports:
      - "8765:8765"
    networks:
      - currency-network
    depends_on:
      - eureka-server
#    environment:
#      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka #write in applicaion.propertis
#      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/ # write in Dockerfile

  eureka-server:
    image: naming-server
    ports:
      - "8761:8761"
    networks:
      - currency-network

  zipkin-server:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - currency-network

networks:
  currency-network: