application:
  configs:
    repository:
      mode: jpa
    log:
      enable: true
    language: fa

spring:
  messages:
    basename: messages/messages
    encoding: UTF-8
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://172.17.0.2:5432/spring_security
    username: postgres
    password: afshar
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect